# Generated by Django 3.2.9 on 2022-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
