# Generated by Django 3.2.9 on 2022-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_purchasedticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='date',
            field=models.DateField(),
        ),
    ]
