# Generated by Django 3.2.9 on 2022-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_purchasedticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedticket',
            name='purchase_amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
