# Generated by Django 3.2.9 on 2022-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_purchasedticket_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
