# Generated by Django 3.2.9 on 2022-01-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_cinemahall_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='cinema_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='cinema.cinemahall'),
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='movie_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_tickets', to='cinema.movieshow'),
        ),
    ]
