# Generated by Django 3.2.9 on 2022-01-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('cinema', '0006_auto_20220116_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExpired',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('last_action', models.DateTimeField(null=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
